#!/usr/bin/env bash
# This script creates a PID file and handles signals properly

echo $$ > /var/run/myscript.pid

sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit
}

sigquit_handler() {
    rm -f /var/run/myscript.pid
    exit
}

trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
