#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word bash

for pid in /proc/[0-9]*
do
    name=$(cat "$pid/comm" 2>/dev/null)
    if [ "$name" = "bash" ]
    then
        echo "$(basename "$pid") $name"
    fi
done
